### ISSUE TITLE
keyPair seems to be ignored

### ISSUE THREAD

**Issue by koinov** [tonlabs/ton-client-js#1]
It looks like keyPair parameter doesn't affect anything while calling deploy or run.

Have two key pairs, deployed smart contract, msg.sender in constructor is 0x0, msg.sender on every run changing state is 0x0. both keyPairs can change state of deployed contract.

I suggest there's a default keyPair used or something like that.

**Comment by melsomino** [comment]
Can you give a code snippet to reproduce?
