### ISSUE TITLE
lib-react-native невалидное название android пакета

### ISSUE THREAD

**Issue by qwertys318** [tonlabs/ton-client-js#176]
android/src/main/AndroidManifest.xml
В манифесте андроида указано название пакета “ton”.
Он не может так называться и должен иметь хотя бы одну точку.
Согласно https://developer.android.com/guide/topics/manifest/manifest-element#package рекомендуется использовать обратное написание доменного имени разработчика.

В эмуляторе приложение собирается и работает. При попытке собрать apk релиз получаем ошибку:
 AAPT: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'ton'.

Пробовал переименовать вручную во что-то вроде com.ton, переложить файлы. В этом случае приложение собирается, устанавливается, но не запускается 🙁

**Comment by melsomino** [comment]
https://github.com/tonlabs/ton-client-js/pull/178
