### ISSUE TITLE
yarn add @tonclient/lib-react-native postinstall script error

### ISSUE THREAD

**Issue by qwertys318** [tonlabs/ton-client-js#177]
При подключении пакета @tonclient/lib-react-native пытается скачать библиотеки в несуществующие папки и падает:
https://github.com/tonlabs/ton-client-js/blob/fd2f809b9fb64f2e046f02257cea1c42d4a83ef4/packages/lib-react-native/install.js#L119

**Comment by g9d** [comment]
Should be fixed at 1dc4ff5258020dffcd51b377d05846a1303851c5
