### ISSUE TITLE
@tonclient/lib-web browser cache of tonclient.wasm

### ISSUE THREAD

**Issue by qwertys318** [tonlabs/ton-client-js#182]
Probably, by following line, tonclient.wasm can be cached by browser and it's problem on updates:
https://github.com/tonlabs/ton-client-js/blob/ad8000b42897d911284e5e2d67b12dd228d14642/packages/lib-web/lib/index-template.js#L126
Please, check it and add hash or something to address.
Thank you

**Comment by elasticLove1** [comment]
Because cash policy depends on a specific web  server,  so the responsibility of naming and placing of binary artifacts  is on the website developer.
We have added documentation how to configure name/place of binary artifact here https://github.com/tonlabs/ton-client-js#setup-library
