### ISSUE TITLE
Local js application

### ISSUE THREAD

**Issue by qwertys318** [tonlabs/ton-client-js#215]
Using 'fetch' to get tonclient.wasm makes impossible to run js applications locally without any webserver:
https://github.com/tonlabs/ton-client-js/blob/a1d43ede6e3186d58c6fbb03e98655018bd606db/packages/lib-web/lib/index-template.js#L126

Any ideas to solve this problem?
Thank you.

**Comment by Systerr** [comment]
Own implementation i think for now :(

**Comment by melsomino** [comment]
https://github.com/tonlabs/ton-client-js/commit/58baf080a24a2cb93d73c4fb80b34823d8dbe51a
