### ISSUE TITLE
Using @tonclient/core and @tonclient/lib-web in SSR application

### ISSUE THREAD

**Issue by velialiev** [tonlabs/ton-client-js#219]
Do you have plans to add support for SSR to @tonclient/core and @tonclient/lib-web? I'm using this library inside my Next.js app and getting a lot of errors related to using web-specific API inside node environment (ReferenceError for Blob, URL, etc.)

**Comment by melsomino** [comment]
All you need is to use `lib-node` instead of `lib-web` on SSR environment.
