### ISSUE TITLE
[TypeScript] AbiData: key type

### ISSUE THREAD

**Issue by velialiev** [tonlabs/ton-client-js#224]
Key in AbiData interface have to have bigint type, but this type isn't supported in JSON. This leads to problem in using JSON ABI. Is it possible to change this type to bigint | number?

![image](https://user-images.githubusercontent.com/55160134/120218112-f2606b00-c241-11eb-8af1-bff54c7ed1b7.png)
![image](https://user-images.githubusercontent.com/55160134/120218487-79154800-c242-11eb-9e24-9371aa1eb3bb.png)
![image](https://user-images.githubusercontent.com/55160134/120218516-86323700-c242-11eb-80d6-2c76724cbe41.png)

**Comment by AlexeyVavilin** [comment]
Fixed in [1.16](https://github.com/tonlabs/ton-client-js/pull/222/files#diff-68fe73a814d05ec0b85acbabdae63431ed70f7c1ba4ed62897fb8e60ddeebc8fR2012)
