### ISSUE TITLE
Keypair derivation from secret key works wrong

### ISSUE THREAD

**Issue by pavlovdog** [tonlabs/ton-client-js#230]
Here's the sample code

```
  const secret = '59ad891197c4eee4ecf156470ecfd2ab42abc89e069f243874a88bcf74f002cb';
  const keyPair = await client.crypto.nacl_sign_keypair_from_secret_key({
    secret
  });
  
  console.log(keyPair);
```

The keypair in the output is wrong. Looks like the `secret` is actual secret concatenated with `public`:

```
{
  public: '88674ff490dab330f2dc1b09374bdf4e4366e707a78db810ac741383be35616e',
  secret: '59ad891197c4eee4ecf156470ecfd2ab42abc89e069f243874a88bcf74f002cb88674ff490dab330f2dc1b09374bdf4e4366e707a78db810ac741383be35616e'
}
```

**Comment by WebElZeN** [comment]
> Here's the sample code
> 
> ```
>   const secret = '59ad891197c4eee4ecf156470ecfd2ab42abc89e069f243874a88bcf74f002cb';
>   const keyPair = await client.crypto.nacl_sign_keypair_from_secret_key({
>     secret
>   });
>   
>   console.log(keyPair);
> ```
> 
> The keypair in the output is wrong. Looks like the `secret` is actual secret concatenated with `public`:
> 
> ```
> {
>   public: '88674ff490dab330f2dc1b09374bdf4e4366e707a78db810ac741383be35616e',
>   secret: '59ad891197c4eee4ecf156470ecfd2ab42abc89e069f243874a88bcf74f002cb88674ff490dab330f2dc1b09374bdf4e4366e707a78db810ac741383be35616e'
> }
> ```  const secret = '59ad891197c4eee4ecf156470ecfd2ab42abc89e069f243874a88bcf74f002cb';
  const keyPair = await client.crypto.nacl_sign_keypair_from_secret_key({
    secret
  });
  
  console.log(keyPair);

**Comment by alex-novikov-1990** [comment]
This is by design. See also: https://crypto.stackexchange.com/questions/54353/why-are-nacl-secret-keys-64-bytes-for-signing-but-32-bytes-for-box
