### ISSUE TITLE
Call of `convertAddress` method with Cyrillic (also Chinese) symbols lead to a crash on mobile devices

### ISSUE THREAD

**Issue by savelichalex** [tonlabs/ton-client-js#91]
Suppose following code:
```javascript
Client.contracts.convertAddress({
  address: 'ылвоаиывлоиаыловиалоывиалоывиалоывиалоывиалоыиав', // Just a long random string with Cyrillic symbols
  convertTo: 'Hex', // Not sure if it only hex, but I tested with it
});
```
This call lead to a crash on mobile devices.

Right now I use a workaround, I just filter incoming address with a RegExp - `/[^:0-9a-zA-Z\-_+/=]/` , but it would be great if the library did it, that could prevent a library users from unpredictable crashes.

**Comment by elasticLove1** [comment]
Thank you, we will fix it in the upcoming releases

**Comment by elasticLove1** [comment]
Fixed
